# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu"
SPDX-License-Identifier = "0BSD"
path = [
  ".devcontainer/devcontainer.json",
  ".vscode/settings.json.orig",
  "README.md",
]
