# SPDX-FileCopyrightText: 2025 Samuel Wu
#
# SPDX-License-Identifier: MIT-0

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 Samuel Wu"
SPDX-License-Identifier = "MIT-0"
path = [
  ".devcontainer/devcontainer.json",
  ".vscode/settings.json.orig",
  "README.md",
]
